/** Баррель API (shared/api): http/rpc клиенты */
export * from './httpClient'
export * from './rpcClient'
export * from './auth'
export * from './user'
export * from './metaClient'
export * from './resourceClient'
export * from './reportClient'
export * from './dtjDataClient'
export * from './orgStructureClient'
